Fix asset/check  && Add helm test functionality (#37)
* add helm test functionality

iter README

cleanup readme ordering and spacing

make chart non-required when test is true, include tests in helm diff output

replace quote usage in chart check

make test pod logs optional, false by default

test and delete cannot both be true - to prevent future craziness

* bump version

* new feature VERSION change

* wip

* stabalized

* iter

* remove syntax error causing check json return to always be empty

* make check a lil saner

* put back log msg

* remove pipefail, add some helpful fail information

Co-authored-by: David Kohl <dkohl@aptosolutions.com>
Co-authored-by: David Kohl <dkohl@vonage.com>

diff --git a/assets/check b/assets/check
--- a/assets/check
+++ b/assets/check
@@ -1,7 +1,6 @@
 #!/bin/bash
 
 set -e
-set -o pipefail
 
 exec 3>&1 # make stdout available as fd 3 for the result
 exec 1>&2 # redirect all output to stderr for logging
@@ -14,27 +13,46 @@ cat > $payload <&0
 
 # Prepare
 setup_resource $payload
-echo "Resource setup successful."
+echo "Resource setup successful." 
+
 
 # Parse parameters
 namespace=$(jq -r '.source.namespace // "default"' < $payload)
+namespace_overwrite=$(jq -r '.params.namespace // ""' < $payload)
+current_namespace=$(jq -r '.version.namespace' < $payload || true)
 release=$(jq -r '.source.release // ""' < $payload)
-current_rev=$(jq -r '.version.revision // "0"' < $payload || true)
+release_overwrite=$(jq -r '.params.release // ""' < $payload)
 current_release=$(jq -r '.version.release' < $payload || true)
+
+if [ -f "$source/$namespace_overwrite" ]; then
+  namespace=$(cat $source/$namespace_overwrite)
+elif [ -n "$namespace_overwrite" ]; then
+  namespace=$namespace_overwrite
+fi
+
+if [ -z "$namespace" ]; then
+  release="$current_namespace"
+fi
+
+if [ -f "$source/$release_overwrite" ]; then
+  release=$(cat $source/$release_overwrite)
+elif [ -n "$release_overwrite" ]; then
+  release=$release_overwrite
+fi
 
 if [ -z "$release" ]; then
   release="$current_release"
 fi
 
-if [ "$release"]
-  then
-  if [ $current_rev -eq "0" ]; then
-    last_rev=$($helm_bin history --max 20 $release --namespace $namespace -o json | jq -r '.[-1].revision')
-    jq -s "map({\"revision\": \"$last_rev\", \"release\": \"$release\"})" >&3
-  else
-    rev_list=$($helm_bin history --max 20 $release --namespace $namespace -o json | jq -r '.[].revision')
-    echo $rev_list | jq -R '.' | jq -s "map({\"revision\": ., \"release\": \"$release\"})" >&3
+if [ "$release" ] ; then
+  revision=$($helm_bin history --max 20 --namespace $namespace $release 2>/dev/null | grep -i 'deployed' | awk '{print $1}' )
+  if [ "$revision" ] ; then
+    echo $revision | jq -R '.' | jq -s "map({\"revision\": ., \"release\": \"$release\"})" >&3
+    exit 0
   fi
-else
-  echo '[]' | jq . >&3
 fi
+
+# if we get here we couldnt find a revision to return so we bail - this is a good thing
+# since check should fail if its configuration cant point to a verifiable state.
+echo "Unable to confirm any revision for namspace: $namespace & release: $release" 
+exit 1
diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -30,6 +30,7 @@ debug=$(jq -r '.params.debug // "false"' < $payload)
 replace=$(jq -r '.params.replace // "false"' < $payload)
 delete=$(jq -r '.params.delete // "false"' < $payload)
 test=$(jq -r '.params.test // "false"' < $payload)
+test_logs=$(jq -r '.params.test_logs // "false"' < $payload)
 purge=$(jq -r '.params.purge // "false"' < $payload)
 devel=$(jq -r '.params.devel // "false"' < $payload)
 force=$(jq -r '.params.force // "false"' < $payload)
@@ -41,8 +42,13 @@ wait=$(jq -r '.params.wait // 0' < $payload)
 check_is_ready=$(jq -r '.params.check_is_ready // "false"' < $payload)
 timeout=$(jq -r '.params.timeout // "5m0s"' < $payload)
 
-if [ -z "$chart" ] && [[ "$delete" == "false" ]]; then
+if [[ "$test" == "false" ]] && [[ "$delete" == "false" ]] && [ -z "$chart" ] ; then
   echo "invalid payload (missing chart)"
+  exit 1
+fi
+
+if [[ "$test" == "true" ]] && [[ "$delete" == "true" ]] ; then
+  echo "invalid payload ( test and delete cannot both be true )"
   exit 1
 fi
 
@@ -178,7 +184,7 @@ helm_upgrade() {
 
   helm_args=("${upgrade_args[@]}" "${overridden_args[@]}")
   helm_echo_args=("${upgrade_args[@]}" "${scrubbed_overridden_args[@]}")
-  helm_diff_args=("${upgrade_diff_args[@]}" "${overridden_args[@]}" "--suppress-secrets")
+  helm_diff_args=("${upgrade_diff_args[@]}" "${overridden_args[@]}" "--suppress-secrets" "--include-tests" )
 
   if [[ -d "$chart_full" ]]; then
     helm_depup_args=("dependency" "update" "$chart_full")
@@ -225,8 +231,26 @@ helm_delete() {
 }
 
 helm_test() {
-  echo "To be implemented"
-  exit 1
+  if [ -z "$release" ]; then
+    echo "invalid payload (missing release if test=true)"
+    exit 1
+  fi
+  
+  if [ "$debug" = true ]; then
+    test_args+=("--debug")
+  fi
+  
+  test_args+=("--namespace=$namespace" "test" "$release" "--timeout=$timeout")
+ 
+  if [ "$test_logs" = true ] ; then
+    test_args+=("--logs")
+  fi
+
+  logfile="/tmp/log"
+  mkdir -p /tmp
+
+  echo "Running command helm ${test_args[@]} | tee $logfile"
+  $helm_bin ${test_args[@]} | tee $logfile
 }
 
 if [ "$delete" = true ]; then
